### ISSUE TITLE
Two processes cannot use tree-sitter-ng simultaneously

### ISSUE THREAD

**Issue by XYZboom** [bonede/tree-sitter-ng#61]
**Describe the bug**
If one process is using tree closer ng, another process will not be able to use it.

**Expected behavior**
Multiple processes can use tree-sitter-ng simultaneously

**OS and Java version**
 - OS: [Windows 11]
 - Java version: [17]

**Exception in the second process**
The native String "另一个程序正在使用此文件，进程无法访问。" in this Exception means "Another program is using this file and the process cannot access it.".
```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at MainKt$main$1$jobs$1$1.invokeSuspend(Main.kt:559)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:113)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:89)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:589)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:823)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:720)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:707)
Caused by: java.lang.RuntimeException: java.io.FileNotFoundException: C:\Users\lenovo\.tree-sitter\lib\x86_64-windows-tree-sitter.dll (另一个程序正在使用此文件，进程无法访问。)
	at org.treesitter.utils.NativeUtils.loadLib(NativeUtils.java:130)
	at org.treesitter.TSParser.<clinit>(TSParser.java:27)
	... 9 more
Caused by: java.io.FileNotFoundException: C:\Users\lenovo\.tree-sitter\lib\x86_64-windows-tree-sitter.dll (另一个程序正在使用此文件，进程无法访问。)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:293)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:235)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:184)
	at org.treesitter.utils.NativeUtils.loadLib(NativeUtils.java:126)
	... 10 more
```

**Comment by XYZboom** [comment]
Maybe we can store the lib file in a temp directory.
```java
static private Path getLibStorePath(){
        String userDefinedPath = System.getProperty("tree-sitter-lib");
//  maybe we can use java.io.tmpdir
        if(userDefinedPath == null){
            return Path.of(System.getProperty("user.home") ,".tree-sitter");
        }
        return Path.of(userDefinedPath);
    }
```

**Comment by XYZboom** [comment]
To be more radical, I may also have the need for multiple threads to use the parser together

**Comment by XYZboom** [comment]
[hs_err_pid52292.log](https://github.com/user-attachments/files/18048223/hs_err_pid52292.log)
a log file when use tree-sitter-ng in mutiple threads

**Comment by bonede** [comment]
Hi, thanks for reporting.

NativeUtils#loadLib is not thread-safe currently. I'm planning to fix this in the next release.

Before that, you may need to handle the synchronization manually.

**Comment by XYZboom** [comment]
Thank you for your reply. I have temporarily resolved this issue by **setting different "tree closer lib" values for each process**. I hope this solution will be helpful to those who see this issue in the future.

**Comment by brookite** [comment]
This issue is still relevant for Windows. Even on library version 0.24.5

**Comment by brookite** [comment]
I've got this exception
```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.vstu.meaningtree.languages.CppLanguage.<init>(CppLanguage.java:66)
	at org.vstu.meaningtree.languages.CppTranslator.<init>(CppTranslator.java:13)
	at org.example.Main.main(Main.java:10)
Caused by: java.lang.RuntimeException: java.io.FileNotFoundException: C:\Users\brook\.tree-sitter\lib\x86_64-windows-tree-sitter.dll (Процесс не может получить доступ к файлу, так как этот файл занят другим процессом)
	at org.treesitter.utils.NativeUtils.loadLib(NativeUtils.java:154)
	at org.treesitter.TSParser.<clinit>(TSParser.java:27)
	... 3 more
Caused by: java.io.FileNotFoundException: C:\Users\brook\.tree-sitter\lib\x86_64-windows-tree-sitter.dll (Процесс не может получить доступ к файлу, так как этот файл занят другим процессом)
	at java.base/java.io.RandomAccessFile.open0(Native Method)
	at java.base/java.io.RandomAccessFile.open(RandomAccessFile.java:356)
	at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:273)
	at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:223)
	at org.treesitter.utils.NativeUtils.loadLib(NativeUtils.java:135)
	... 4 more
```

**Comment by volyx** [comment]
https://github.com/volyx/java-tree-sitter-native/tree/main/helloworld


```
  helloworld git:(main) ✗ ./target/helloworld                                                       
Exception in thread "main" java.lang.ExceptionInInitializerError
        at com.example.App.main(App.java:15)
        at java.base@24/java.lang.invoke.LambdaForm$DMH/sa346b79c.invokeStaticInit(LambdaForm$DMH)
Caused by: java.lang.RuntimeException: Can't open lib/x86_64-macos-tree-sitter.dylib
        at org.treesitter.utils.NativeUtils.readLib(NativeUtils.java:89)
        at org.treesitter.utils.NativeUtils.loadLib(NativeUtils.java:123)
        at org.treesitter.TSParser.<clinit>(TSParser.java:27)
        ... 2 more
```

**Comment by bonede** [comment]
This harder than I thought, plan to fix this in future release with more solid test cases.
